### ISSUE TITLE
Type inference error in a function I tried to write: Is it expected at the moment?

### ISSUE THREAD

**Issue by maxeonyx** [jamii/imp#5] opened 2022-01-27 02:30 UTC
The inference works through one application of a function with boxing, but not the second application. The error that comes up is "Could not infer the type of abstract arg."

The `uniquify_col` function here works when applied once, but not when applied twice. 

```zig
db:
| :foo, 42
| :foo, "fooey"
| :foo, 21
| :bar, "yo", "pro"
| :bar, "hi";

skip_col: ?a some;
first_col: ?a ?b a;
unbox: ?@a a;
unbox_first_col: ?@a ?n a;

// get all the unique values in one column, and return the other columns so we can do it for them as well
uniquify_col: ?@all ?n (
    (
    |   :uniqed, all :uniqed
    |   :uniqed, n, all :todo first_col
    |   :todo, all :todo skip_col
    )@, n+1
);

initial_state: (:todo, db)@, 0;

// (1) works, (2) gives a type inference error:

// (1)
initial_state uniquify_col unbox_first_col

// (2)
// initial_state uniquify_col uniquify_col unbox_first_col

// my goal is for this to work:
// (fix initial_state uniquify_col) unbox_first_col
```

**Comment by jamii** [comment] 2022-01-27 04:54
Man, I need to add stack traces...

**Comment by jamii** [comment] 2022-01-27 04:59
I think the problem is that `first_col` expects two columns, so eg `"yo" first_col` returns `?b "yo"` rather than just `"yo"`. And then we can't infer the type of `b` because it isn't applied to anything.

The error messages are terrible though.

**Comment by jamii** [comment] 2022-01-27 05:01
I don't think it's possible to write `first_col` for mixed-arity sets at the moment. The proposed `columns` and `pivot` functions at the end of https://www.scattered-thoughts.net/writing/imp-heterogenous-types/ would make this much easier.

**Comment by jamii** [comment] 2022-01-27 05:09
If you knew the db also had two columns though then the whole program could just be `db ?a ?b a | b`.

**Comment by maxeonyx** [comment] 2022-01-27 05:59
Cool, thanks - interesting that you don't think it's possible to do this with any number of columns at the moment.

I didn't think about just doing `a | b`! :)

**Comment by maxeonyx** [comment] 2022-01-27 09:30
Actually the correct program for this program with two columns is 
```zig
db ?a ?b (:1, a) | (:2, b)
```
because we want the unique values for each column separated.

**Comment by jamii** [comment] 2022-02-05 01:22
I'm going to close this because it won't apply to v3.

**Closed as completed by jamii** 2022-02-05 01:22 UTC
